title = "Lenny Kiruthu"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Params.author]
  name = "Lenny Kiruthu"
  bio = "Who Cares"
  avatar = ""

[Params]
  description = "Lenny" # Description of your site
  copyright = "Lenny Kiruthu"
  opengraph = true
  schema = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" # Load Google Fonts
  customCSS = ["css/img-gallery.css"] # Include custom CSS files
  customJS = ["js/glightbox.js"] # Include custom JS files

[Params.logo]
  image = "images/logo/finance_dollar.png"
  title = "Lenny Kiruthu"
  subtitle = "Algo Trading Consultant" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.style.vars]
  highlightColor = "#960018"
  fontFamilyPrimary = "Roboto, Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Author] # Used in authorbox
  name = "Lenny Kiruthu"
  bio = "As an Algo Trading Consultant, I specialize in designing, optimizing, and deploying algorithmic trading strategies that leverage data-driven insights to maximize market opportunities. With a strong foundation in quantitative analysis and a deep understanding of market dynamics, I work closely with clients to develop customized trading algorithms tailored to their unique financial goals. My expertise in scripting languages, including Python and Pine Script, allows me to create robust, high-frequency trading systems that ensure precision and efficiency. I am committed to staying at the forefront of technological advancements in the trading industry, continuously refining strategies to adapt to evolving market conditions and deliver superior results. Whether you're a seasoned trader looking to enhance your strategies or a firm seeking to implement cutting-edge algorithmic solutions, I provide the guidance and technical expertise needed to succeed in the fast-paced world of algorithmic trading."
  avatar = "img/profile-picture.png"

[Params.widgets.social]
  cached = true # activate cache if true
  # Enable parts of social widget
  # linkedin = "erik-ngigi"
  # github = "ErikNgigi"
  email = "kiruthulenny@gmail.com"
  youtube = "@lennykiruthu"
